[client]
showErrorDetails = true
maxMessageSize = 200

[server]
maxUploadSize = 200
enableXsrfProtection = true
port = 10000
headless = true

[logger]
level = "info"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"
